### ISSUE TITLE
PSone Pins

### ISSUE THREAD

**Issue by Madad1996** [kalymos/PsNee#10]
Is this compatible to the PSone, if yes which pins i should use?

**Comment by ramapcsx2** [comment]
PAL or NTSC-U/J machine?
PAL requires the boot patch, which means more cables.
In any case, the install diagrams include this model. The diagram is for PAL.

**Comment by Madad1996** [comment]
Cant find the Pins on the Board...
https://imgur.com/gallery/9Iwq6

**Comment by Madad1996** [comment]
SCPh-102

**Comment by ramapcsx2** [comment]
Ah, this is the more rare PM-41(2) board. 
You'll have to use a multimeter and find something to solder to. Google image search has some old modchip installation pictures for these boards. They can help you find your pins.
The 2 BIOS pins will be the same, so will Vcc and Gnd.
Data is usually marked '6' in old diagrams. It will be one side of an smd capacitor. 
WFCK is marked '5' and is a test point pad.
SUBQ is pin24, SQCK is pin26 on the HC-05 (IC304).
