### ISSUE TITLE
PM-41(2) PAL different layout

### ISSUE THREAD

**Issue by klode82** [kalymos/PsNee#21]
I cannot find all points to made solders on my PCB. I'm working with an Arduino Nano with ATMega.

This is the PCB: [https://imgur.com/tgAdHI5](url)

**Comment by ramapcsx2** [comment]
Try this:
https://i.imgur.com/68TnVRw.jpg

**Comment by klode82** [comment]
Thanks a lot!, but is not too easy understand where the wired are connected on the Nano, and a wire is hidden (the pins 4 and 5...)
Thanks to your image, I've realized this one.

https://imgur.com/a/g9mkhkB

Please, can you help me to identify D4 and D5?

Thanks.

**Comment by ramapcsx2** [comment]
Sorry, I don't have a board out to find the pins.

**Comment by klode82** [comment]
Don't worry, I've found all Pins.

https://imgur.com/vJZQBQL

I'll try as soon as possible.
