### ISSUE TITLE
ESP8266 Support?

### ISSUE THREAD

**Issue by INVALID-CLIENT** [kalymos/PsNee#24]
Will this be able to work with a ESP8266?

**Comment by ramapcsx2** [comment]
Of course, but you'll have to port it :)

**Comment by INVALID-CLIENT** [comment]
> Of course, but you'll have to port it :)

I'm new with arduinos. How would one possibly port it to the ESP8266? Would I just change the pin layout in the .ino file? Or is there more to it?
