### ISSUE TITLE
PU-23 and ATtiny45

### ISSUE THREAD

**Issue by Jambul46** [kalymos/PsNee#28]
can someone please post me wiring diagram for ATtiny45 i can't find it and i don't want to mess it up.

PS MdN:SCPH-9002 PU-23.

Thanks.

**Comment by Jambul46** [comment]
and i don't understand this
![image](https://user-images.githubusercontent.com/50278139/103468093-dec5dc80-4d55-11eb-802b-769ea5ad2f92.png)

**Comment by kalymos** [comment]
![IMG_20210103_083012](https://user-images.githubusercontent.com/4646148/103473935-5586c800-4d9e-11eb-9032-29bb2084b125.jpg)

**Comment by Jambul46** [comment]
yeah i know but i would need something like this 
![image](https://user-images.githubusercontent.com/50278139/103477714-aa880580-4dc1-11eb-94a6-f94494571594.png)

But TY.

**Comment by Jambul46** [comment]
![PU-23 main top](https://user-images.githubusercontent.com/50278139/103477880-436b5080-4dc3-11eb-90b2-e6ccebca3962.jpg)

Something like this?

**Comment by Jambul46** [comment]
![image](https://user-images.githubusercontent.com/50278139/103478097-bcb77300-4dc4-11eb-95b6-895a7dfdfa5c.png)
?

**Comment by kalymos** [comment]
yes I think that's it, it's been a long time since I modded a ps.

**Comment by Jambul46** [comment]
Ok Thanks.

**Comment by Jambul46** [comment]
just want to ask i have PAL PSone and i the code it says that bios patch is not supported 
and when i put i game it says me "Please Insert PlayStation CD-ROM"

**Comment by Jambul46** [comment]
oh only for PM-41 so  do i have to enable it?

**Comment by Jambul46** [comment]
Nice it work's i had to select default region

**Comment by wyatt8740** [comment]
You can also just get ground off the "disc lid" switch.

Sorry about the miscellaneous gore on this board. It was a parts board I revitalized.

![PU-23 Gore](https://i.imgur.com/snGKb9E.jpg)
