### ISSUE TITLE
Pro Micro pinout column was deleted from readme

### ISSUE THREAD

**Issue by wyatt8740** [kalymos/PsNee#37]
What was the reasoning for deleting the ProMicro column from the table in the README?

It still claims to be "supported" in the readme, but the pinout i tested and contributed was removed in https://github.com/kalymos/PsNee/commit/df44218ea28a6499ee7ff2a0575fc0931ad1dd85 with no explanation given.

Pins 15 and 14 on the ProMicro are not labeled as SCK and MISO on the ProMicro as they are on the Leonardo. They are labeled 15 and 14.

I suspect that's what https://github.com/kalymos/PsNee/issues/31 is asking about.

**Comment by kalymos** [comment]
Hello 
I removed the promicro because it has the same pin-out as the Arduino uno.
iI is true that I should specify, Arduino Uno and ATMega 368
