### ISSUE TITLE
Question  about running mod

### ISSUE THREAD

**Issue by arminsalcin** [kalymos/PsNee#45]
Hello,

Thanks for library, i used attiny85 and programmer avrisp i succesfully burned chip (with no bootloader) and 8Mhz internal clock but after installation i cant run original PAL game, my system is SCPH-101 with PM-41 (2) board it is also NTSC-U console 

Question is : 
- Can we still run original games after chip?
- Will PAL games work after the chip on NTSC console?
- Is burning fuses on attiny really necessary before uploading code via arduino IDE? (I didnt do this part)

**Comment by kalymos** [comment]
Hello,

Overall the answer is yes to all three questions, for the fuses if you
install the Arduino bootloader, and then you burn the program again the
fuses remain.

But normally on SCP-101, you have to run the bios patch, which is not
really possible on ATtiny85.

Sorry

Le dim. 10 sept. 2023 à 20:28, Armin Salčin ***@***.***> a
écrit :

**Comment by arminsalcin** [comment]
Thanks for the quick answer, i got confused by the bios patch [here](https://quade.co/ps1-modchip-guide/psnee/pm-41-2/) It says only if you have PAL SCP-101 to do bios patch, I will try with Arduino pro mini definitely to move out of probably mistakes with burning fuses.
