### ISSUE TITLE
Cannot play ps1 backups with different region than console.

### ISSUE THREAD

**Issue by gufunkt-tacos** [kalymos/PsNee#48]
I just modded my old PS1 (European, PU-22) with an ATtiny85 which has worked perfectly. However, when I tried to play Parasite Eve (the American version), it wouldn't get passed the initial screen. It says "SCEE" as well as "Sony Computer Entertainment America".

**Comment by kalymos** [comment]
It is possible that the game has additional protection, but I don't have
the list in mind, I know for example that "resident evil nemesis" has this
kind of protection.

Le lun. 25 déc. 2023 à 21:29, Саймън Аткинсън ***@***.***> a
écrit :
