### ISSUE TITLE
Docs: Nano: PSNee 3.3v in VIN not working

### ISSUE THREAD

**Issue by The-May** [kalymos/PsNee#51]
I flashed bootloader via SPI and I couldnt get it to work.
I double checked wiring, solder points etc.
After some troubleshooting I found out that SPI VCC worked instead of VIN
This is mentioned in a older Video: https://www.youtube.com/watch?v=mhMCT63-h08

See Picture what i mean:
![image](https://github.com/kalymos/PsNee/assets/47433911/a1f5fc63-7279-4e8a-833c-1b71e3062db5)

Maybe this should be changed (or at least mentioned?) in the modchip installation guide

**Comment by kalymos** [comment]
Thanks for pointing this out to me because I made the same mistake in all
the diagrams, it's fixed 😅
