### ISSUE TITLE
Port code to Tiny avr 0 series

### ISSUE THREAD

**Issue by carmax91** [kalymos/PsNee#52]
It is possible to port the code to the new avr tiny 0 series like ATTINY402?
The old attinyx5 are out of production now and the price become insanely increase... I think it's a better idea to port the code to the newest cheap attinyx02 for the 8 pin chip.
I've given a try, but i can't port the code easly to the new core...

**Comment by kalymos** [comment]
It's probably a good idea to do so. I think the part to modify is the name
of the registers

**Comment by kalymos** [comment]
From memory it is not necessary to use registers, it is that calling the
individual Pinout function for each pin is more resource intensive
