### ISSUE TITLE
How to delete the bootloader ? 

### ISSUE THREAD

**Issue by HanaO00** [kalymos/PsNee#55]
Hello, is the "flash with a programmer" option enough to overwrite the bootloder? Or do i need to make additional modifications to the Arduino?

I think I confused it with the "burn bootloader" option if I use this option will it erase psnee present on the card?

**Comment by kalymos** [comment]
hello
Actually using a programmer for that is enough to remove the bootloader,
and it's the same technique that we use to reinstall it.
I link the simplest technique to have a programmer.
https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP/

**Comment by HanaO00** [comment]
Thanks for your help
