### ISSUE TITLE
Psnee not working help

### ISSUE THREAD

**Issue by 5a796d** [kalymos/PsNee#57]
Can you give me a step by step guide? I have pal 5502 pu-18, pro micro 5v 16mhz (set on arduino to 5v 16mhz) flashed from arduino ide enabling atmega32x4 in the sketch, correctly connected the 4 wires plus power supply on vin pin at 3.5v as per the diagram but it doesn't work, it asks me insert the CD or start the games as if they were audio CDs. With modchip pic12c508 everything works, same thing with unirom cart. Thank you

**Comment by kalymos** [comment]
Sorry for not responding earlier...
I am currently preparing the new version of the chip mode, with completely revised documentation.
Everything is available in this git [https://github.com/kalymos/PSNee_V8/tree/test2](https://github.com/kalymos/PSNee_V8/tree/test2)
